### ISSUE TITLE
👑 [需求]可以制作一个代码生成工具吗？

### ISSUE THREAD

**Issue by sunw31** [jetlinks/jetlinks-ui-antd#1]
### 🥰 需求描述

生成前端react，后端hsweb-framework4，业务代码

### 🧐 解决方案

不知道有没有帮助
https://github.com/xinyu198736/antd-visual-editor

**Comment by Lind-pro** [comment]
正在研究中。。。

**Comment by sunw31** [comment]
> 正在研究中。。。

https://share.weiyun.com/5d0lai5

**Comment by Lind-pro** [comment]
> > 正在研究中。。。
> 
> https://share.weiyun.com/5d0lai5

感谢提供建议。
