### ISSUE TITLE
🐛[BUG] 编辑设备型号时,配置了MQTT认证配置,有时无法显示编辑。

### ISSUE THREAD

**Issue by zhou-hao** [jetlinks/jetlinks-ui-antd#10]
1. 配置了MQTT认证信息
2. 编辑型号
3. 无法编辑认证信息

### 🚑 其他信息
 
![35631587348294_ pic_hd](https://user-images.githubusercontent.com/7791838/79707323-b04ec100-82ee-11ea-96ee-9303183ead4e.jpg)

**Comment by gyf520** [comment]
已解决并提交
