### ISSUE TITLE
🐛[BUG] 规则实例中，删除一个规则后，分页查询失效

### ISSUE THREAD

**Issue by zhou-hao** [jetlinks/jetlinks-ui-antd#105]
删除一个规则，表格数量变多了。

**Comment by zhou-hao** [comment]
![image](https://user-images.githubusercontent.com/7791838/87163149-7db6d200-c2f9-11ea-82a7-d9d4af7815e7.png)

删除后刷新时，没有带任何分页条件，也没有使用界面上带查询条件来进行查询

**Comment by gyf520** [comment]
![image](https://user-images.githubusercontent.com/30947728/87274708-fcd12380-c50e-11ea-8df7-f4ee7261dc21.png)
优化后删除有携带查询条件
