### ISSUE TITLE
多租户资产管理界面，点击查看展示的是所有的设备🐛[BUG]

### ISSUE THREAD

**Issue by cranehovers** [jetlinks/jetlinks-ui-antd#109]
### 🐛 bug 描述

![}JQ1S105ZRA 7_8E74QX8(S](https://user-images.githubusercontent.com/10259043/87162680-d9cd2680-c2f8-11ea-9709-964953897553.png)

多租户资产管理界面，点击查看按钮，展示的是所有的设备
### © 版本信息

- Jetlinks-ui-antd 版本: 20200710晚上拉的最新代码
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by Lind-pro** [comment]
已修复 https://github.com/jetlinks/jetlinks-ui-antd/commit/b84e115d18f905eb72bf091d6b25d3630b6c2db3
