### ISSUE TITLE
🐛[BUG]设备实例->设备详情->日志列表

### ISSUE THREAD

**Issue by LiShiLin4510** [jetlinks/jetlinks-ui-antd#113]
### 🐛 bug 描述
设备实例列表，点击查看到设备详情，点击日志管理进入日志列表页面，显示的日志不是最新的设备日志，当切换页码后再切换到页码1，此时页码1的日志才是最新的日志，该问题时而会出现

### 📷 复现步骤
设备实例->查看->日志列表->切换页码->切换回第一页

### 🏞 期望结果
日志列表第一页的日志为最新的日志信息

### © 版本信息

- Jetlinks-ui-antd 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by gyf520** [comment]
本地测试暂时无法复现，能否把出现问题时的请求截图看一下，本地请求参数中都是会携带排序字段。
![image](https://user-images.githubusercontent.com/30947728/87495397-e4364a00-c683-11ea-8dfb-229073285177.png)

**Comment by LiShiLin4510** [comment]
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jetlinks/jetlinks-ui-antd"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月15日(星期三) 上午10:14
收件人:&nbsp;"jetlinks/jetlinks-ui-antd"<jetlinks-ui-antd@noreply.github.com&gt;;
抄送:&nbsp;"I am a soldier！"<1272745473@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [jetlinks/jetlinks-ui-antd] 🐛[BUG] (#113)





 
本地测试暂时无法复现，能否把出现问题时的请求截图看一下，本地请求参数中都是会携带排序字段。
