### ISSUE TITLE
🐛[BUG]【设备产品】所属品类显示选择&显示问题

### ISSUE THREAD

**Issue by 790712946** [jetlinks/jetlinks-ui-antd#126]
### 🐛 bug 描述
设备产品，新建，选择所属品类，点击选择框后面的删除后，无法从新选择所属品类，一直红字提示

### 📷 复现步骤

1，新建设备产品
2. 选择所属品类
![image](https://user-images.githubusercontent.com/18082424/88129344-71404c80-cc0a-11ea-8c24-5ed8d0e8a843.png)
3.删除所属品类
![image](https://user-images.githubusercontent.com/18082424/88129354-7c937800-cc0a-11ea-8a52-c37becb046c0.png)
![image](https://user-images.githubusercontent.com/18082424/88129370-874e0d00-cc0a-11ea-8ea2-a6f44fe81b7f.png)
4.重新选择所属品类
![image](https://user-images.githubusercontent.com/18082424/88129397-992fb000-cc0a-11ea-832b-78d10378ce7a.png)

### 🏞 期望结果

删除后能够重新选择所属品类

### © 版本信息

- Jetlinks-ui-antd 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by gyf520** [comment]
BUG已修复，更新代码再试一下
