### ISSUE TITLE
🐛[BUG] 设备告警页面记录分页问题

### ISSUE THREAD

**Issue by LiShiLin4510** [jetlinks/jetlinks-ui-antd#135]
### 🐛 bug 描述

设备实例中的设备告警页面，告警日志首次进入现实的日志内容为最早的日志列表，当前换到第二页的时候又显示的是当前最新的日志数据的第二页，按时间排序选择的是由近到远

### 📷 复现步骤

设备实例--》查看--》告警设置--》告警记录
### 🏞 期望结果

在排序为由当前时间开始的情况下，进入告警记录首页显示最新的记录列表
### 💻 复现代码

![image](https://user-images.githubusercontent.com/27464785/88871605-e2a37f00-d24a-11ea-92a5-d48f0a0e9a41.png)

### © 版本信息

- Jetlinks-ui-antd 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by gyf520** [comment]
本地暂未复现，请下次复现后F12截图看一下请求参数
![image](https://user-images.githubusercontent.com/30947728/88893928-acc9bf00-d279-11ea-9364-4b974cf4769c.png)

**Comment by LiShiLin4510** [comment]
![image](https://user-images.githubusercontent.com/27464785/88897439-d7b61200-d27d-11ea-927b-5890425b9cbd.png)

**Comment by gyf520** [comment]
代码什么版本的？建议更新代码重试

**Comment by LiShiLin4510** [comment]
已经更新到最新版本了

**Comment by gyf520** [comment]
如果是本地代码启动的打开这个目录  device/alarm/index.tsx这个文件下  41行到46行截图看一下      还有    334到342截图看一下，如果是docker启动的请更新到 1.4.0版本

**Comment by LiShiLin4510** [comment]
![image](https://user-images.githubusercontent.com/27464785/88898574-80b13c80-d27f-11ea-9400-1d4da19fe6f6.png)
![image](https://user-images.githubusercontent.com/27464785/88898621-8f97ef00-d27f-11ea-8413-9d8f1f86b0ed.png)

**Comment by gyf520** [comment]
建议清一波浏览器缓存试一下，本地暂时无法复现，代码也正常，docker启动的也试过，都无法复现。

**Comment by LiShiLin4510** [comment]
清了一下缓存还是不行，尴尬
