### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by LiShiLin4510** [jetlinks/jetlinks-ui-antd#136]
### 🐛 bug 描述

进入设备实例查看设备，日志管理筛选条件不起作用，筛选条件为空时可以查出全部日志，日志类型和日期选择后筛选出来的为空列表

### 📷 复现步骤

设备实例--》查看--》--》日志管理--》选择日志类型--》选择日期--》查询

### 🏞 期望结果
筛选条件起作用，可以筛选出日志类型的日志，日期区间的日志

### 💻 复现代码

![image](https://user-images.githubusercontent.com/27464785/88876270-7bd79300-d255-11ea-9605-0cae99780570.png)
![image](https://user-images.githubusercontent.com/27464785/88876297-8db93600-d255-11ea-9075-b578b54e6830.png)

### © 版本信息

- Jetlinks-ui-antd 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by zhou-hao** [comment]
#135
