### ISSUE TITLE
👑 [需求] 规则实例查看界面

### ISSUE THREAD

**Issue by zhou-hao** [jetlinks/jetlinks-ui-antd#145]
* [x] 查看运行日志，数据.
* [x] 展示实时日志和数据。

**Comment by zhou-hao** [comment]
*获取规则日志接口*

`GET /rule-engine/instance/{id}/logs`

*获取规则事件接口*

`GET /rule-engine/instance/{id}/events`

*订阅规则实时日志*

`{"topic":"/rule-engine/{instanceId}/{nodeId}/logger/{level}"}`

*订阅规则事件*

事件有: `result`(输出),`complete`(完成),`error`(错误)

`{"topic":"/rule-engine/{instanceId}/{nodeId}/event/{event}"}`

**Comment by zhou-hao** [comment]
获取规则的节点信息:

`GET /rule-engine/instance/{id}/nodes`

**Comment by gyf520** [comment]
![~EE%4{5MGC{B2FO $I{ Z0F](https://user-images.githubusercontent.com/30947728/89270485-fb0e0200-d66d-11ea-8582-4cd767411469.jpg)
