### ISSUE TITLE
🧐[问题]如何修改接口地址呀？

### ISSUE THREAD

**Issue by xlb0479** [jetlinks/jetlinks-ui-antd#158]
### 🧐 问题描述

现在应该是前端和后端要求在同一个域名下吧？如何修改后端的接口地址呢？

### 💻 示例代码

无

### 🚑 其他信息

无

**Comment by Lind-pro** [comment]
这是前后端分离项目。
1、不需要在同一个域名下。
2、开发环境下参考：``` config/proxy.ts ```;生产环境在nginx下配置代理，参考：``` docker/nginx.conf ```
