### ISSUE TITLE
👑 [优化]【租户端】首页设备列表优化

### ISSUE THREAD

**Issue by gyf520** [jetlinks/jetlinks-ui-antd#163]
### 🥰 需求描述
![image](https://user-images.githubusercontent.com/30947728/89968048-7b8fbc80-dc85-11ea-8c2e-f4e71bd3ed6e.png)
将此表格修改为下方表格
![image](https://user-images.githubusercontent.com/30947728/89968160-b98ce080-dc85-11ea-896b-215fa4f44172.png)
![image](https://user-images.githubusercontent.com/30947728/89968176-c14c8500-dc85-11ea-8ca7-b498f50ce978.png)

**Comment by Lind-pro** [comment]
fix https://github.com/jetlinks/jetlinks-ui-antd/commit/97bdad3d38698808b7263670b667c21279c59c3d
