### ISSUE TITLE
本地npm run-script build打包项目，通过NGINX容器部署项目，系统登录成功后跳转404🧐[问题]

### ISSUE THREAD

**Issue by LiShiLin4510** [jetlinks/jetlinks-ui-antd#168]
### 🧐 问题描述

本地npm run-script build打包项目，通过NGINX容器部署项目，系统登录成功后跳转404，有其他页面也会如此跳转，console报/user/detail404

### 💻 示例代码
![image](https://user-images.githubusercontent.com/27464785/90121953-35bf1b00-dd8f-11ea-9185-b4c2e36959a7.png)
![image](https://user-images.githubusercontent.com/27464785/90122203-80d92e00-dd8f-11ea-862e-505be274bee5.png)
nginx配置如下
![image](https://user-images.githubusercontent.com/27464785/90122327-b2ea9000-dd8f-11ea-8f88-1990efe28d97.png)

**Comment by Lind-pro** [comment]
检查后端服务器是否启动成功了

**Comment by LiShiLin4510** [comment]
启动了，并且打印了相应的日志






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jetlinks/jetlinks-ui-antd"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月13日(星期四) 晚上6:24
收件人:&nbsp;"jetlinks/jetlinks-ui-antd"<jetlinks-ui-antd@noreply.github.com&gt;;
抄送:&nbsp;"I am a soldier！"<1272745473@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jetlinks/jetlinks-ui-antd] 本地npm run-script build打包项目，通过NGINX容器部署项目，系统登录成功后跳转404🧐[问题] (#168)





 
检查后端服务器是否启动成功了

**Comment by zhou-hao** [comment]
后端是最新代码么

**Comment by LiShiLin4510** [comment]
后端是最新的代码

**Comment by zhou-hao** [comment]
创建新用户也这样？

**Comment by LiShiLin4510** [comment]
是的，创建新用户也是这样

**Comment by zhou-hao** [comment]
远程看看吧

**Comment by LiShiLin4510** [comment]
ok

**Comment by Lind-pro** [comment]
Emmm

发自我的iPhone

**Comment by LiShiLin4510** [comment]
461 802 137    4749

**Comment by zhou-hao** [comment]
破案 。代码没更新完。

**Comment by LiShiLin4510** [comment]
我为什么一直没更新完呢，我也是这么操作的

**Comment by zhou-hao** [comment]
可能有冲突，没有注意到，所以就没更新成功
