### ISSUE TITLE
🐛[BUG]【设备】设备详情界面内可视化中日期显示问题

### ISSUE THREAD

**Issue by gyf520** [jetlinks/jetlinks-ui-antd#175]
### 🐛 bug 描述
日期格式问题

### © 版本信息

- Jetlinks-ui-antd 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
![856O8`B7X4E{HRL5VUKI~6D](https://user-images.githubusercontent.com/30947728/90728510-9900fe00-e2f7-11ea-8b6f-ef690f6b5eb6.jpg)

**Comment by Lind-pro** [comment]
@gyf520 咋复现
![image](https://user-images.githubusercontent.com/18098618/92064149-7b3f9880-edcf-11ea-93d3-57f25f05e491.png)

**Comment by gyf520** [comment]
线条上不是有点吗？鼠标放上去，会显示点位信息，点位信息中的日期没格式化------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Lind&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年9月3日(星期四) 上午10:23
收件人:&nbsp;&quot;jetlinks/jetlinks-ui-antd&quot;<jetlinks-ui-antd@noreply.github.com&gt;;
抄送:&nbsp;&quot;Gaiys&quot;<admin@gaiys.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [jetlinks/jetlinks-ui-antd] 🐛[BUG]【设备】设备详情界面内可视化中日期显示问题 (#175)
