### ISSUE TITLE
🐛[BUG] 通知模版保存后,查询条件失效。

### ISSUE THREAD

**Issue by zhou-hao** [jetlinks/jetlinks-ui-antd#197]
![image](https://user-images.githubusercontent.com/7791838/92546537-622e6000-f285-11ea-8f65-6434eb9b56e7.png)

**Comment by Lind-pro** [comment]
fix https://github.com/jetlinks/jetlinks-ui-antd/commit/1a82b5b6a7ba590560da0ff7532a91d11021517d
