### ISSUE TITLE
👑 [需求]设备模拟器

### ISSUE THREAD

**Issue by gyf520** [jetlinks/jetlinks-ui-antd#203]
### 🥰 需求描述
按照按照原型“jetlinks原型0907”做设备模拟器相关功能（注：原型在team群文件中）

**Comment by Lind-pro** [comment]
#https://github.com/jetlinks/jetlinks-pro/issues/130

**Comment by gyf520** [comment]
![image](https://user-images.githubusercontent.com/30947728/94357071-23433b80-00c8-11eb-9de5-1ab4d71aae63.png)

编辑无法回显
