### ISSUE TITLE
🐛[BUG]登录

### ISSUE THREAD

**Issue by gyf520** [jetlinks/jetlinks-ui-antd#206]
### 🐛 bug 描述
登录界面有时点击第一次时无法正常登录，需要重新点击第二次才能正常登录

### © 版本信息

- Jetlinks-ui-antd 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by Lind-pro** [comment]
fix https://github.com/jetlinks/jetlinks-ui-antd/commit/d4426f5a9d3700ef6dfbfa41243ae67539b4cee5
