### ISSUE TITLE
🐛[BUG]项目本地运行后 大屏数据 和 模拟测试 没有子菜单，点击路由报错

### ISSUE THREAD

**Issue by wbsndbf** [jetlinks/jetlinks-ui-antd#215]
### 🐛 bug 描述

项目本地运行后 大屏数据 和 模拟测试 没有子菜单，点击路由报错

### 📷 复现步骤

npm install -> npm run start:dev 运行起来后大屏数据和模拟测试 没有子菜单

### 🏞 期望结果

正常显示路由配置菜单

### 💻 复现代码
 {
                        path: 'data-screen',
                        name: '大屏数据',
                        icon: 'desktop',
                        tenant: ['admin'],
                        iconfont: 'icon-icon-',
                    
                        routes: [
                            {
                                path: '/data-screen/category',
                                name: '分类管理',
                                icon: 'appstore',
                                tenant: ['admin'],
                                iconfont: 'icon-category-search-fill',
                                authority: ['big-screen','admin'],
                                version: 'pro',
                                component: './data-screen/category',
                            },
                            {
                                path: '/data-screen/screen',
                                name: '大屏管理',
                                icon: 'fund',
                                tenant: ['admin'],
                                iconfont: 'icon-screen',
                                authority: ['big-screen','admin'],
                                version: 'pro',
                                component: './data-screen/screen',
                            }
                        ]
                    },
                    {
                        path: 'simulator',
                        name: '模拟测试',
                        icon: 'bug',
                        authority: ['network-simulator', 'admin'],
                        routes: [
                            {
                                path: '/simulator/device',
                                name: '设备模拟器',
                                icon: 'paper-clip',
                                authority: ['network-simulator', 'admin'],
                                component: './simulator/device',
                            }
                        ]
                    },
如图为下拉，未成改动，运行起来后路由菜单如下图：
![QQ截图20201104101840](https://user-images.githubusercontent.com/40485635/98061375-b40af500-1e86-11eb-9c31-0a76bf7d55c7.png)
![QQ截图20201104101840](https://user-images.githubusercontent.com/40485635/98061449-de5cb280-1e86-11eb-9674-54dbf51a2c7b.png)

就很困惑，这是直接下拉的代码未成任何改动（仅按照文档修改了后端接口api）

### © 版本信息

- Jetlinks-ui-antd 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by Lind-pro** [comment]
社区版不支持大屏数据和模拟测试功能
