### ISSUE TITLE
🐛[BUG]租户管理->租户端->里面部分Tabs会提示权限不足，无法访问 

### ISSUE THREAD

**Issue by FanstasCw** [jetlinks/jetlinks-ui-antd#226]
### 🐛 bug 描述

租户访问->租户管理->租户端->里面部分Tabs（资产信息、成员管理、查看权限
）会提示权限不足，无法访问，该租户分配了“租户管理-租户端”权限

### 📷 复现步骤

超级管理员，新建租户，分配“租户管理-租户端”权限和其他基础权限，租户登录->打开租户管理->租户端->打开部分Tabs

### 🏞 期望结果

如果该租户没有部分Tabs的访问权限，该用户不出现部分Tabs,如果该租户有权限，不提示权限不足，无法访问

### 💻 复现代码
前后端使用的1.7版本源码启动的，截至2020-12-15 15点此时的代码，只增加了redis的密码和启用了自动加载通过依赖引入的协议包，其他代码均无修改,

### © 版本信息

- Jetlinks-ui-antd 版本: [e.g. 1.7.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. Centos7]

### 🚑 其他信息
 Gif
![test](https://user-images.githubusercontent.com/23033459/102184674-ca2abd00-3eea-11eb-9983-ae8ce0cd869b.gif)

**Comment by zhou-hao** [comment]
更新前端代码没

**Comment by FanstasCw** [comment]
> 更新前端代码没

更新了，202012-15 15点那时仓库最新的代码还是有问题

**Comment by zhou-hao** [comment]
看看是哪些接口提示权限不足



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: FanstasCw <notifications@github.com&gt;
发送时间: 2020年12月16日 08:27
收件人: jetlinks/jetlinks-ui-antd <jetlinks-ui-antd@noreply.github.com&gt;
抄送: 老周 <zh.sqy@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[jetlinks/jetlinks-ui-antd] ��[BUG]租户管理-&gt;租户端-&gt;里面部分Tabs会提示权限不足，无法访问  (#226)





  
更新前端代码没
  
更新了，202012-15 15点那时仓库最新的代码还是有问题

**Comment by FanstasCw** [comment]
> 看看是哪些接口提示权限不足 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: FanstasCw <notifications@github.com&gt; 发送时间: 2020年12月16日 08:27 收件人: jetlinks/jetlinks-ui-antd <jetlinks-ui-antd@noreply.github.com&gt; 抄送: 老周 <zh.sqy@qq.com&gt;, Comment <comment@noreply.github.com&gt; 主题: 回复：[jetlinks/jetlinks-ui-antd] ��[BUG]租户管理-&gt;租户端-&gt;里面部分Tabs会提示权限不足，无法访问 (#226) 更新前端代码没 更新了，202012-15 15点那时仓库最新的代码还是有问题 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

前天你不是远程我电脑上看了，目前就是资产管理、成员管理（今天测试没有报错）、查看权限，基本上都会提示权限不足
查看权限：http://192.168.0.22/jetlinks/permission/_query/no-paging?paging=false
![image](https://user-images.githubusercontent.com/23033459/102292444-21c73800-3f80-11eb-9790-69d5cd3599d5.png)

http://192.168.0.22/jetlinks/autz-setting/_query/no-paging?paging=false&terms%5B0%5D.column=dimensionTarget&terms%5B0%5D.value=296542955367e99f9387519f6d500a6d
![image](https://user-images.githubusercontent.com/23033459/102292423-14aa4900-3f80-11eb-9300-5bdfd9c95014.png)

资产管理：http://192.168.0.22/jetlinks/protocol/_count?terms%5B0%5D.column=id%24assets&terms%5B0%5D.value=%7B%22tenantId%22%3A%22296542955367e99f9387519f6d500a6d%22%2C%22assetType%22%3A%22protocol%22%7D&terms%5B1%5D.column=state&terms%5B1%5D.value=1
![image](https://user-images.githubusercontent.com/23033459/102292481-31468100-3f80-11eb-9f70-d08bd27c2437.png)
操作GIF
![test2](https://user-images.githubusercontent.com/23033459/102292503-402d3380-3f80-11eb-8944-cb2b241fee20.gif)

**Comment by zhou-hao** [comment]
没有分配对应都权限吧

**Comment by FanstasCw** [comment]
> 没有分配对应都权限吧

今天刚发现一个问题，昨天更新了最新代码没注意权限里面多了两项权限，也没仔细看超级管理员界面的租户管理（管理端），租户管理-管理端首页显示了成员数，但进入后，成员管理里面没有对应的成员，同时租户管理-租户端，依旧显示没有权限，同时基本信息界面没有数据显示，反倒是租户管理租户端->成员管理可以看到对应的成员
![test2](https://user-images.githubusercontent.com/23033459/102295246-f3e4f200-3f85-11eb-9966-527fd74b7190.gif)
