### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by zhoufa** [jetlinks/jetlinks-ui-antd#231]
### 🐛 bug 描述

新建产品时，非导入， 进入产品查看页面，点击物模型，会出现错误，
product-save-Detail.ts文件 => setProperties(metadata.properties);
metadata.properties为空，导致product-save-definition-Properties.tsx文件的data为undefined，会出现报错，
改成setProperties(metadata.properties?metadata.properties:[]);之后，不会报错，其它的比如事件，功能没改同样会的报错，
新建产品设备时，当没有事件定义（Event）时，device-instance-editor-detail-Status.tsx的const events = metadata.events      .map会报错，因为metadata没有events属性，demo环境上没有报错，下载master分支会报错

### © 版本信息

- Jetlinks-ui-antd 版本: master
- umi 版本
- 浏览器环境 谷歌
- 开发环境 window10 专业版

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/10864000/105673047-6bf8ed00-5f20-11eb-9ece-6881a98c0045.png)

**Comment by Lind-pro** [comment]
尽快修复。
