### ISSUE TITLE
👑 [需求]文档补充有关跳转外部链接的配置方法

### ISSUE THREAD

**Issue by tiankazma** [jetlinks/jetlinks-ui-antd#232]
### 🥰 需求描述

实际对接项目时, 市场需要对接外部的身份认证或登录页

### 🧐 解决方案

在文档中添加code demo 的相关说明, 引导开发人员对接外部登录页面

**Comment by Lind-pro** [comment]
http://doc.jetlinks.cn/dev-guide/sso.html#%E6%B5%81%E7%A8%8B
平台支持统一单点登录
