### ISSUE TITLE
🐛[BUG]地理位置, 浏览器报错

### ISSUE THREAD

**Issue by tiankazma** [jetlinks/jetlinks-ui-antd#233]
### 🐛 bug 描述

设备管理-地理位置, 浏览器console报错

### 📷 复现步骤

1. 登录jetlinks
2. 点击进入'设备管理-地理位置'
3. 打开'开发者工具-Console', 查看报错

### 🏞 期望结果

报错消失, 且不影响原有功能

### © 版本信息

- Jetlinks-ui-antd 版本: 4.0.0
- umi 版本 : 2.13.13
- 浏览器环境 : Google Chrome 88.0.4324.182
- 开发环境 : windows
### 🚑 其他信息

![image](https://user-images.githubusercontent.com/44330404/108788614-51fc0a00-75b3-11eb-9963-d44750b901a8.png)

![image](https://user-images.githubusercontent.com/44330404/108788794-c8007100-75b3-11eb-9742-506e5142908b.png)

**Comment by Lind-pro** [comment]
这些只是警告⚠️

**Comment by tiankazma** [comment]
> 这些只是警告⚠️

怎么说呢, 这些东西, 不能过审.... 没事, 我再看看吧, 不影响功能就好

**Comment by Lind-pro** [comment]
> > 这些只是警告⚠️
> 
> 怎么说呢, 这些东西, 不能过审.... 没事, 我再看看吧, 不影响功能就好

解决这些警告也很简单，根据他提示的进行修复即可。
