### ISSUE TITLE
🧐[问题]地理位置, 查询无效果

### ISSUE THREAD

**Issue by tiankazma** [jetlinks/jetlinks-ui-antd#234]
### 🧐 问题描述

在设备管理-地理位置页面, 按设备ID查询, 页面无效果

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/44330404/108790770-78707400-75b8-11eb-8b05-11ccdc30323c.png)

**Comment by gyf520** [comment]
你这个设备是否有设置标签，数据类型为：地理位置，并且设置了经纬度，或者定义属性为：地理位置，并且设备上报了经纬度
