### ISSUE TITLE
🧐[问题]地理位置 - 设备告警, 展示内容不理解

### ISSUE THREAD

**Issue by tiankazma** [jetlinks/jetlinks-ui-antd#235]
### 🧐 问题描述

地理位置 - 设备告警, 点开告警记录后, 页面模态框显示为告警JSON文件, 求主要参数的实际意义详解

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/44330404/108798061-c8a30280-75c7-11eb-91fd-25df88d060b3.png)

**Comment by gyf520** [comment]
列表只是做简单的展示，点击后查看的是发生告警的数据，与设备或产品内展示内容是一致的
