### ISSUE TITLE
🧐[问题] 用戶接口返回用户名为``sb`` 是否为故意辱骂体验用户

### ISSUE THREAD

**Issue by h7ml** [jetlinks/jetlinks-ui-antd#253]
### 🧐 问题描述

用戶接口返回用户名为``sb`` 是否为故意辱骂体验用户

### 💻 示例代码

http://demo.jetlinks.cn/jetlinks/authorize/me 

``` json
{
    "message": "success",
    "result": {
        "user": {
            "id": "1229586247651758080",
            "username": "test",
   

1.          "name": "sb",

            "type": "user"
        },
        "permissions": [
            {
                "id": "visualization",
                "name": "可视化管理",
                "actions": [
                    "query"
                ],
                "dataAccesses": []
            },
            {
                "id": "tenant-side-manager",
                "name": "租户管理-租户端",
                "actions": [
                    "query"
                ],
                "dataAccesses": [],
                "options": {
                    "type": [
                        "tenant"
                    ]
                }
            },
            {
                "id": "media-device",
                "name": "国标设备",
                "actions": [
                    "query"
                ],
                "dataAccesses": [],
                "options": {}
            },
            {
                "id": "device-simulator",
                "name": "设备模拟器",
                "actions": [
                    "query"
                ],
                "dataAccesses": []
            },
            {
                "id": "autz-setting",
                "name": "权限分配",
                "actions": [
                    "query"
                ],
                "dataAccesses": []
            },
            {
                "id": "tenant-manager",
                "name": "租户管理-管理端",
                "actions": [
                    "query"
                ],
                "dataAccesses": [],
                "options": {
                    "type": [
                        "tenant"
                    ]
                }
            },
            {
                "id": "dashboard",
                "name": "仪表盘",
                "actions": [
                    "query"
                ],
                "dataAccesses": []
            },
            {
                "id": "media-server",
                "name": "流媒体服务",
                "actions": [
                    "query"
                ],
                "dataAccesses": []
            },
            {
                "id": "access-logger",
                "name": "访问日志",
                "actions": [
                    "query"
                ],
                "dataAccesses": []
            },
            {
                "id": "system-logger",
                "name": "系统日志",
                "actions": [
                    "query"
                ],
                "dataAccesses": []
            },
            {
                "id": "index-report",
                "name": "首页统计",
                "actions": [
                    "query"
                ],
                "dataAccesses": []
            },
            {
                "id": "device-instance",
                "name": "设备实例",
                "actions": [
                    "query"
                ],
                "dataAccesses": [],
                "options": {
                    "type": [
                        "system",
                        "business",
                        "api",
                        "tenant"
                    ]
                }
            },
            {
                "id": "device-api-product",
                "name": "设备数据API(根据设备型号)",
                "actions": [
                    "query-device-events",
                    "query-device-properties",
                    "query-device-events-format",
                    "query-device-log"
                ],
                "dataAccesses": [],
                "options": {
                    "type": []
                }
            },
            {
                "id": "dueros-product",
                "name": "小度产品管理",
                "actions": [
                    "query"
                ],
                "dataAccesses": []
            },
            {
                "id": "tenant-test",
                "name": "多租户测试",
                "actions": [
                    "add"
                ],
                "dataAccesses": [],
                "options": {
                    "type": [
                        "tenant"
                    ]
                }
            },
            {
                "id": "network-config",
                "name": "网络组件配置",
                "actions": [
                    "query"
                ],
                "dataAccesses": []
            },
            {
                "id": "dictionary",
                "name": "数据字典",
                "actions": [
                    "query"
                ],
                "dataAccesses": []
            },
            {
                "id": "geo-manager",
                "name": "地理信息管理",
                "actions": [
                    "find-geo-json",
                    "query",
                    "find-geo-object",
                    "find-geo"
                ],
                "dataAccesses": [],
                "options": {
                    "type": []
                }
            },
            {
                "id": "media-stream",
                "name": "流媒体信息",
                "actions": [
                    "start"
                ],
                "dataAccesses": []
            },
            {
                "id": "firmware-upgrade-task-manager",
                "name": "固件升级任务管理",
                "actions": [
                    "query"
                ],
                "dataAccesses": []
            },
            {
                "id": "opc-client",
                "name": "OPC-UA客户端",
                "actions": [
                    "query"
                ],
                "dataAccesses": []
            },
            {
                "id": "template",
                "name": "通知模板",
                "actions": [
                    "query"
                ],
                "dataAccesses": []
            },
            {
                "id": "network-simulator",
                "name": "网络模拟器",
                "actions": [
                    "query"
                ],
                "dataAccesses": []
            },
            {
                "id": "visualization-component",
                "name": "可视化组件管理",
                "actions": [
                    "query"
                ],
                "dataAccesses": []
            },
            {
                "id": "certificate",
                "name": "证书管理",
                "actions": [
                    "query"
                ],
                "dataAccesses": []
            },
            {
                "id": "report-layout",
                "name": "报表配置",
                "actions": [
                    "query"
                ],
                "dataAccesses": []
            },
            {
                "id": "aliyun-bridge",
                "name": "阿里云接入配置",
                "actions": [
                    "query"
                ],
                "dataAccesses": []
            },
            {
                "id": "open-api",
                "name": "openApi客户端",
                "actions": [
                    "query"
                ],
                "dataAccesses": []
            },
            {
                "id": "system-config",
                "name": "系统配置",
                "actions": [
                    "query"
                ],
                "dataAccesses": []
            },
            {
                "id": "device-alarm",
                "name": "设备告警",
                "actions": [
                    "query"
                ],
                "dataAccesses": [],
                "options": {
                    "type": [
                        "tenant"
                    ]
                }
            },
            {
                "id": "rule-model",
                "name": "规则引擎-模型",
                "actions": [
                    "query"
                ],
                "dataAccesses": []
            },
            {
                "id": "device-group",
                "name": "设备分组",
                "actions": [
                    "query"
                ],
                "dataAccesses": [],
                "options": {}
            },
            {
                "id": "notifier",
                "name": "通知管理",
                "actions": [
                    "query"
                ],
                "dataAccesses": [],
                "options": {
                    "type": [
                        "tenant"
                    ]
                }
            },
            {
                "id": "rule-instance",
                "name": "规则引擎-实例",
                "actions": [
                    "query"
                ],
                "dataAccesses": []
            },
            {
                "id": "dimension",
                "name": "维度管理",
                "actions": [
                    "query"
                ],
                "dataAccesses": [],
                "options": {
                    "type": [
                        "system"
                    ]
                }
            },
            {
                "id": "device-api",
                "name": "设备数据API",
                "actions": [
                    "query-device-events",
                    "query-device-properties-latest",
                    "agg-device-property",
                    "query",
                    "get-detail-list",
                    "get-device-info",
                    "query-device-properties",
                    "query-device-log",
                    "get-detail"
                ],
                "dataAccesses": [],
                "options": {
                    "type": []
                }
            },
            {
                "id": "oauth2-client",
                "name": "OAuth2客户端管理",
                "actions": [
                    "query"
                ],
                "dataAccesses": []
            },
            {
                "id": "device-opt-api",
                "name": "设备操作API",
                "actions": [
                    "read-property"
                ],
                "dataAccesses": [],
                "options": {
                    "type": [
                        "api"
                    ]
                }
            },
            {
                "id": "firmware-manager",
                "name": "固件管理",
                "actions": [
                    "query"
                ],
                "dataAccesses": []
            },
            {
                "id": "message-gateway",
                "name": "消息网关",
                "actions": [
                    "subscribe",
                    "query"
                ],
                "dataAccesses": []
            },
            {
                "id": "rule-scene",
                "name": "场景管理",
                "actions": [
                    "query"
                ],
                "dataAccesses": []
            },
            {
                "id": "vis-configuration",
                "name": "组态管理",
                "actions": [
                    "query",
                    "get"
                ],
                "dataAccesses": [],
                "options": {}
            },
            {
                "id": "gb28181-cascade",
                "name": "GB28181级联网关",
                "actions": [
                    "query"
                ],
                "dataAccesses": []
            },
            {
                "id": "permission",
                "name": "权限管理",
                "actions": [
                    "query"
                ],
                "dataAccesses": [],
                "options": {
                    "type": [
                        "tenant"
                    ]
                }
            },
            {
                "id": "menu",
                "name": "菜单管理",
                "actions": [
                    "query"
                ],
                "dataAccesses": []
            },
            {
                "id": "protocol-supports",
                "name": "协议管理",
                "actions": [
                    "query"
                ],
                "dataAccesses": [],
                "options": {
                    "type": [
                        "tenant",
                        "api"
                    ]
                }
            },
            {
                "id": "report-config",
                "name": "报表开发",
                "actions": [
                    "query"
                ],
                "dataAccesses": []
            },
            {
                "id": "device-gateway",
                "name": "设备网关",
                "actions": [
                    "query"
                ],
                "dataAccesses": []
            },
            {
                "id": "device-product",
                "name": "设备型号",
                "actions": [
                    "query"
                ],
                "dataAccesses": [],
                "options": {
                    "type": [
                        "tenant"
                    ]
                }
            },
            {
                "id": "organization",
                "name": "机构管理",
                "actions": [
                    "query"
                ],
                "dataAccesses": [],
                "options": {
                    "type": [
                        "tenant"
                    ]
                }
            },
            {
                "id": "device-firmware-manager",
                "name": "设备固件信息管理",
                "actions": [
                    "query"
                ],
                "dataAccesses": [],
                "options": {}
            },
            {
                "id": "opc-device-bind",
                "name": "OPC-UA设备绑定",
                "actions": [
                    "query"
                ],
                "dataAccesses": []
            },
            {
                "id": "device-category",
                "name": "设备分类",
                "actions": [
                    "query"
                ],
                "dataAccesses": []
            },
            {
                "id": "media-channel",
                "name": "流媒体通道",
                "actions": [
                    "query"
                ],
                "dataAccesses": [],
                "options": {
                    "type": [
                        "api"
                    ]
                }
            },
            {
                "id": "user-token",
                "name": "用户令牌信息管理",
                "actions": [
                    "query"
                ],
                "dataAccesses": []
            },
            {
                "id": "big-screen",
                "name": "大屏管理",
                "actions": [
                    "query"
                ],
                "dataAccesses": [],
                "options": {
                    "type": [
                        "api"
                    ]
                }
            }
        ],
        "dimensions": [
            {
                "id": "1229586247651758080",
                "name": "1229586247651758080",
                "type": "user"
            }
        ],
        "attributes": {}
    },
    "status": 200,
    "timestamp": 1628218787054
}
```

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/55233292/128449901-2a6d18a6-73fc-49e1-bbca-50515b3f8d6c.png)

![image](https://user-images.githubusercontent.com/55233292/128449705-401ed95a-a1c9-463a-90e3-17e773975f07.png)

**Comment by zhou-hao** [comment]
演示用户自行修改的。如介意，请本地运行体验。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: h7ml ***@***.***&gt;
发送时间: 2021年8月6日 11:05
收件人: jetlinks/jetlinks-ui-antd ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[jetlinks/jetlinks-ui-antd] ��[问题] 用戶接口返回用户名为``sb`` 是否为故意辱骂体验用户 (#253)





 
🧐 问题描述
 
用戶接口返回用户名为sb 是否为故意辱骂体验用户
 
💻 示例代码
 
http://demo.jetlinks.cn/jetlinks/authorize/me
 {     "message": "success",     "result": {         "user": {             "id": "1229586247651758080",             "username": "test",     1.          "name": "sb",             "type": "user"         },         "permissions": [             {                 "id": "visualization",                 "name": "可视化管理",                 "actions": [                     "query"                 ],                 "dataAccesses": []             },             {                 "id": "tenant-side-manager",                 "name": "租户管理-租户端",                 "actions": [                     "query"                 ],                 "dataAccesses": [],                 "options": {                     "type": [                         "tenant"                     ]                 }             },             {                 "id": "media-device",                 "name": "国标设备",                 "actions": [                     "query"                 ],                 "dataAccesses": [],                 "options": {}             },             {                 "id": "device-simulator",                 "name": "设备模拟器",                 "actions": [                     "query"                 ],                 "dataAccesses": []             },             {                 "id": "autz-setting",                 "name": "权限分配",                 "actions": [                     "query"                 ],                 "dataAccesses": []             },             {                 "id": "tenant-manager",                 "name": "租户管理-管理端",                 "actions": [                     "query"                 ],                 "dataAccesses": [],                 "options": {                     "type": [                         "tenant"                     ]                 }             },             {                 "id": "dashboard",                 "name": "仪表盘",                 "actions": [                     "query"                 ],                 "dataAccesses": []             },             {                 "id": "media-server",                 "name": "流媒体服务",                 "actions": [                     "query"                 ],                 "dataAccesses": []             },             {                 "id": "access-logger",                 "name": "访问日志",                 "actions": [                     "query"                 ],                 "dataAccesses": []             },             {                 "id": "system-logger",                 "name": "系统日志",                 "actions": [                     "query"                 ],                 "dataAccesses": []             },             {                 "id": "index-report",                 "name": "首页统计",                 "actions": [                     "query"                 ],                 "dataAccesses": []             },             {                 "id": "device-instance",                 "name": "设备实例",                 "actions": [                     "query"                 ],                 "dataAccesses": [],                 "options": {                     "type": [                         "system",                         "business",                         "api",                         "tenant"                     ]                 }             },             {                 "id": "device-api-product",                 "name": "设备数据API(根据设备型号)",                 "actions": [                     "query-device-events",                     "query-device-properties",                     "query-device-events-format",                     "query-device-log"                 ],                 "dataAccesses": [],                 "options": {                     "type": []                 }             },             {                 "id": "dueros-product",                 "name": "小度产品管理",                 "actions": [                     "query"                 ],                 "dataAccesses": []             },             {                 "id": "tenant-test",                 "name": "多租户测试",                 "actions": [                     "add"                 ],                 "dataAccesses": [],                 "options": {                     "type": [                         "tenant"                     ]                 }             },             {                 "id": "network-config",                 "name": "网络组件配置",                 "actions": [                     "query"                 ],                 "dataAccesses": []             },             {                 "id": "dictionary",                 "name": "数据字典",                 "actions": [                     "query"                 ],                 "dataAccesses": []             },             {                 "id": "geo-manager",                 "name": "地理信息管理",                 "actions": [                     "find-geo-json",                     "query",                     "find-geo-object",                     "find-geo"                 ],                 "dataAccesses": [],                 "options": {                     "type": []                 }             },             {                 "id": "media-stream",                 "name": "流媒体信息",                 "actions": [                     "start"                 ],                 "dataAccesses": []             },             {                 "id": "firmware-upgrade-task-manager",                 "name": "固件升级任务管理",                 "actions": [                     "query"                 ],                 "dataAccesses": []             },             {                 "id": "opc-client",                 "name": "OPC-UA客户端",                 "actions": [                     "query"                 ],                 "dataAccesses": []             },             {                 "id": "template",                 "name": "通知模板",                 "actions": [                     "query"                 ],                 "dataAccesses": []             },             {                 "id": "network-simulator",                 "name": "网络模拟器",                 "actions": [                     "query"                 ],                 "dataAccesses": []             },             {                 "id": "visualization-component",                 "name": "可视化组件管理",                 "actions": [                     "query"                 ],                 "dataAccesses": []             },             {                 "id": "certificate",                 "name": "证书管理",                 "actions": [                     "query"                 ],                 "dataAccesses": []             },             {                 "id": "report-layout",                 "name": "报表配置",                 "actions": [                     "query"                 ],                 "dataAccesses": []             },             {                 "id": "aliyun-bridge",                 "name": "阿里云接入配置",                 "actions": [                     "query"                 ],                 "dataAccesses": []             },             {                 "id": "open-api",                 "name": "openApi客户端",                 "actions": [                     "query"                 ],                 "dataAccesses": []             },             {                 "id": "system-config",                 "name": "系统配置",                 "actions": [                     "query"                 ],                 "dataAccesses": []             },             {                 "id": "device-alarm",                 "name": "设备告警",                 "actions": [                     "query"                 ],                 "dataAccesses": [],                 "options": {                     "type": [                         "tenant"                     ]                 }             },             {                 "id": "rule-model",                 "name": "规则引擎-模型",                 "actions": [                     "query"                 ],                 "dataAccesses": []             },             {                 "id": "device-group",                 "name": "设备分组",                 "actions": [                     "query"                 ],                 "dataAccesses": [],                 "options": {}             },             {                 "id": "notifier",                 "name": "通知管理",                 "actions": [                     "query"                 ],                 "dataAccesses": [],                 "options": {                     "type": [                         "tenant"                     ]                 }             },             {                 "id": "rule-instance",                 "name": "规则引擎-实例",                 "actions": [                     "query"                 ],                 "dataAccesses": []             },             {                 "id": "dimension",                 "name": "维度管理",                 "actions": [                     "query"                 ],                 "dataAccesses": [],                 "options": {                     "type": [                         "system"                     ]                 }             },             {                 "id": "device-api",                 "name": "设备数据API",                 "actions": [                     "query-device-events",                     "query-device-properties-latest",                     "agg-device-property",                     "query",                     "get-detail-list",                     "get-device-info",                     "query-device-properties",                     "query-device-log",                     "get-detail"                 ],                 "dataAccesses": [],                 "options": {                     "type": []                 }             },             {                 "id": "oauth2-client",                 "name": "OAuth2客户端管理",                 "actions": [                     "query"                 ],                 "dataAccesses": []             },             {                 "id": "device-opt-api",                 "name": "设备操作API",                 "actions": [                     "read-property"                 ],                 "dataAccesses": [],                 "options": {                     "type": [                         "api"                     ]                 }             },             {                 "id": "firmware-manager",                 "name": "固件管理",                 "actions": [                     "query"                 ],                 "dataAccesses": []             },             {                 "id": "message-gateway",                 "name": "消息网关",                 "actions": [                     "subscribe",                     "query"                 ],                 "dataAccesses": []             },             {                 "id": "rule-scene",                 "name": "场景管理",                 "actions": [                     "query"                 ],                 "dataAccesses": []             },             {                 "id": "vis-configuration",                 "name": "组态管理",                 "actions": [                     "query",                     "get"                 ],                 "dataAccesses": [],                 "options": {}             },             {                 "id": "gb28181-cascade",                 "name": "GB28181级联网关",                 "actions": [                     "query"                 ],                 "dataAccesses": []             },             {                 "id": "permission",                 "name": "权限管理",                 "actions": [                     "query"                 ],                 "dataAccesses": [],                 "options": {                     "type": [                         "tenant"                     ]                 }             },             {                 "id": "menu",                 "name": "菜单管理",                 "actions": [                     "query"                 ],                 "dataAccesses": []             },             {                 "id": "protocol-supports",                 "name": "协议管理",                 "actions": [                     "query"                 ],                 "dataAccesses": [],                 "options": {                     "type": [                         "tenant",                         "api"                     ]                 }             },             {                 "id": "report-config",                 "name": "报表开发",                 "actions": [                     "query"                 ],                 "dataAccesses": []             },             {                 "id": "device-gateway",                 "name": "设备网关",                 "actions": [                     "query"                 ],                 "dataAccesses": []             },             {                 "id": "device-product",                 "name": "设备型号",                 "actions": [                     "query"                 ],                 "dataAccesses": [],                 "options": {                     "type": [                         "tenant"                     ]                 }             },             {                 "id": "organization",                 "name": "机构管理",                 "actions": [                     "query"                 ],                 "dataAccesses": [],                 "options": {                     "type": [                         "tenant"                     ]                 }             },             {                 "id": "device-firmware-manager",                 "name": "设备固件信息管理",                 "actions": [                     "query"                 ],                 "dataAccesses": [],                 "options": {}             },             {                 "id": "opc-device-bind",                 "name": "OPC-UA设备绑定",                 "actions": [                     "query"                 ],                 "dataAccesses": []             },             {                 "id": "device-category",                 "name": "设备分类",                 "actions": [                     "query"                 ],                 "dataAccesses": []             },             {                 "id": "media-channel",                 "name": "流媒体通道",                 "actions": [                     "query"                 ],                 "dataAccesses": [],                 "options": {                     "type": [                         "api"                     ]                 }             },             {                 "id": "user-token",                 "name": "用户令牌信息管理",                 "actions": [                     "query"                 ],                 "dataAccesses": []             },             {                 "id": "big-screen",                 "name": "大屏管理",                 "actions": [                     "query"                 ],                 "dataAccesses": [],                 "options": {                     "type": [                         "api"                     ]                 }             }         ],         "dimensions": [             {                 "id": "1229586247651758080",                 "name": "1229586247651758080",                 "type": "user"             }         ],         "attributes": {}     },     "status": 200,     "timestamp": 1628218787054 }
 
🚑 其他信息

**Comment by h7ml** [comment]
![image](https://user-images.githubusercontent.com/55233292/128450492-ca84ea93-be0a-46d5-9ab5-428b6ca3b635.png)

1. 用戶修改后，再次登录 。用户名依旧 
2. 不介意

**Comment by zhou-hao** [comment]
权限缓存
