### ISSUE TITLE
🐛[BUG] 机构保存BUG

### ISSUE THREAD

**Issue by zhou-hao** [jetlinks/jetlinks-ui-antd#32]
复现步骤:

1. 创建顶级机构
2. 添加子机构
3. 修改顶级机构
4. 保存后数据无法获取

原因:

保存顶级机构时,把子机构的parentId携带进去了。

修复建议:
1. 编辑时,如果没有parentId,则不提交parentId字段.
2. 编辑时,ID设置为只读.

**Comment by Lind-pro** [comment]
搞定
