### ISSUE TITLE
👑 [优化]多租户UI优化

### ISSUE THREAD

**Issue by zhou-hao** [jetlinks/jetlinks-ui-antd#68]
**列表页**

* [x] 描述信息与实际数据不符
* [x] 状态列, 正常绿色，禁用橙色
* [x] 成员数列，绿色
* [x] 开始时间列应该是创建时间
* [x] 禁用按钮无效。调用保存按钮。传入state即可。
* [x] 将查看操作按钮放到第一个

**详情页**
资产信息:

* [x] 图标与实际不符
* [x] 编辑资产-添加资产后，界面未刷新。添加按钮改成蓝色
* [x] 退出界面后对应的资产数量未刷新。
* [x] 增加 协议资产,对应协议管理, 添加资产时,使用接口:  `/protocol/supports`获取列表。

成员管理:

* [x] 添加成员后,返回列表页未刷新
* [x]  搜索条件中名称改为姓名
* [x] 列表操作也增加查看资产，链接到资产信息中，查看成员资产
* [x] 如果选择了成员则只编辑/查看成员的资产

**Comment by Lind-pro** [comment]
closes 成员管理

**Comment by Lind-pro** [comment]
closes：列表页

**Comment by Lind-pro** [comment]
closes:资产信息

**Comment by Lind-pro** [comment]
fix #68

**Comment by Lind-pro** [comment]
closed #5392b504409111f819191427d52709d72bf6127a
