### ISSUE TITLE
🐛[BUG]设备实例指定条件查询bug

### ISSUE THREAD

**Issue by turandot2017** [jetlinks/jetlinks-ui-antd#70]
### 🐛 bug 描述
   设备实例列表中, 可根据条件进行查询
   查询请求参数有问题
   如: 当选择某个机构时, 会按机构查询, 再次选择时, 发送请求参数未变化
   
### 📷 复现步骤
  1. 选择一个机构进行查询
  2. 再次选择另一个机构进行查询
  看查询结果

### 🏞 期望结果
  1. 可以根据输入参数的变化, 向后端提交不同的入参
  2. 设备名称支持模糊查询, 现在的模糊查询有问题 

### © 版本信息

- Jetlinks-ui-antd 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by gyf520** [comment]
设备名称支持模糊查询，想模糊查询需要自己添加%，例如：测试设备，模糊查询时：%测试设备%
