### ISSUE TITLE
👑 [需求] 设备列表中增加全文搜索引擎

### ISSUE THREAD

**Issue by turandot2017** [jetlinks/jetlinks-ui-antd#74]
### 🥰 需求描述

1. 设备列表是最常用的功能, 当设备较多时, 查询/过滤均不方便
2. 系统已支持  `标签` , 标签可视为扩展字段, 用户需要在标签中进行过滤, 查找
3. 目前的系统强关联Elasticsearch, 它最大的特点是支持搜索引擎
以上, 建议把设备及相关数据整成一个大text + Id, 存放到 ES中, 利用ES的全文搜索, 得到 Id 列表后再到数据库中取列表其它字段
写ES应该很快, 做一个`重建全文检索`功能, 即可在设备表页面增加一个 search 框
"什么都可输入查询"

### 🧐 解决方案

增加`重建全文检索`功能 + `search` 框

### 🚑 其他信息

类似wox中的重建索引
![image](https://user-images.githubusercontent.com/27339520/85016346-23b06a00-b19c-11ea-853b-7efbe0cd8500.png)

**Comment by zhou-hao** [comment]
暂时不考虑全文检索，设备查询条件在后面会进行优化。
