### ISSUE TITLE
按照markdown安装依赖缺失🐛[BUG]

### ISSUE THREAD

**Issue by Alex-lsky** [jetlinks/jetlinks-ui-antd#779]
### 🐛 bug 描述
npm install和cnpm install 均无法安装以下依赖
* @formily/react-schema-renderer in ./src/components/ArrayPanel/index.tsx
* @formily/react-shared-components in ./src/components/ArrayPanel/index.tsx
* @formily/shared in ./src/components/ArrayPanel/index.tsx
* prop-types in ./src/pages/analysis/components/Hide/autoHide.tsx, ./src/pages/device/gateway/LineWrap.tsx and 1 other
* styled-components in ./src/components/ArrayPanel/index.tsx
* umi-plugin-locale/lib/locale in ./src/pages/.umi/LocaleWrapper.jsx

环境：
windows11
node.js :16.9
cnpm : 9.01

### © 版本信息
系统：windows11
 node.js :16.9
 cnpm : 9.01
IDE：webstorm: 2022.3.2

- Jetlinks-ui-antd 版本: [e.g. 4.0.0]
- 
- umi 版本
- 2.13.13

- 开发环境 [e.g. mac OS]
windows11
### 🚑 其他信息

![image](https://user-images.githubusercontent.com/59161352/217704707-7c0c57f8-acba-454b-9cdd-18113cc4f285.png)

**Comment by Wzyyy98** [comment]
用yarn安装试试

**Comment by Alex-lsky** [comment]
使用yarn install  安装成功

**Comment by Alex-lsky** [comment]
使用yarn install 安装成功
