### ISSUE TITLE
👑 [需求]地理位置查询条件优化

### ISSUE THREAD

**Issue by turandot2017** [jetlinks/jetlinks-ui-antd#78]
### 🥰 需求描述

现有的地理位置视图, 设备过滤条件需要优化
支持所属部门过滤/设备状态过滤/名称模糊查询/标签内容过虑

### 🧐 解决方案
  增加多常用的过滤条件, 增加用户体验
  最好让地图有"图层"的实现 

### 🚑 其他信息
 参考界面图:
![image](https://user-images.githubusercontent.com/27339520/85089859-41bab080-b216-11ea-9100-7d144367622e.png)

**Comment by zhou-hao** [comment]
目前地理位置需要调整的地方还比较多，已加入候选任务。
