### ISSUE TITLE
🐛[BUG] 结构体类型在设备运行状态中展示问题

### ISSUE THREAD

**Issue by zhou-hao** [jetlinks/jetlinks-ui-antd#84]
在设备型号配置的地方如果添加了结构体类型的属性。在查看运行状态时，当设备上报数据，页面直接白屏。

**Comment by wangzheng0723** [comment]
bug已在本地复现
![image](https://user-images.githubusercontent.com/15624265/85261325-907a7b80-b49e-11ea-87c9-13118da8e3e7.png)

**Comment by gyf520** [comment]
已修复并提交

**Comment by gyf520** [comment]
https://github.com/jetlinks/jetlinks-ui-antd/commit/231db5950b7e15f3c971035f5446cd42b2fb2654
