### ISSUE TITLE
🐛[BUG]HTTP协议网关

### ISSUE THREAD

**Issue by 790712946** [jetlinks/jetlinks-ui-antd#85]
### 🐛 bug 描述

HTTP协议网关选择路由的时候，点删除路由导致页面白屏

### 📷 复现步骤

选择一个HTTP网关，点击编辑，协议路由点击新增，在点击删除，白屏

### © 版本信息

- Jetlinks-ui-antd 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by Lind-pro** [comment]
增加标题
