### ISSUE TITLE
🐛[BUG]设备运行状态中数据展示不完整

### ISSUE THREAD

**Issue by cranehovers** [jetlinks/jetlinks-ui-antd#89]
### 🐛 bug 描述

在设备运行状态中数据中，每个数据项展示不完整，比如说光照度是6位数，加上单位，基本上有十个字，前端只展示了1个字就自动省略了，建议完整展示数据

### © 版本信息

- Jetlinks-ui-antd 版本:  master- e75f3dc
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![数据展示不完整](https://user-images.githubusercontent.com/10259043/85556300-4b4e7900-b659-11ea-8dd1-3c24250e61a3.png)

**Comment by gyf520** [comment]
![image](https://user-images.githubusercontent.com/30947728/85935573-fc3c6880-b924-11ea-8856-d11702452fbd.png)
之前优化过此界面，后面修复了此问题，请重新更新一下代码再重试。
