### ISSUE TITLE
🐛[BUG]告警日志界面的下拉列表会重复出现告警设置信息

### ISSUE THREAD

**Issue by cranehovers** [jetlinks/jetlinks-ui-antd#94]
### 🐛 bug 描述

在设备实例的告警界面，点击启动或者停止某个告警的话，告警日志界面的下拉列表里，就会增加一个新的告警设置信息
### © 版本信息

- Jetlinks-ui-antd 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![告警界面点击启动或停止](https://user-images.githubusercontent.com/10259043/86126554-16d33500-bb11-11ea-81b3-55ae2aa7e415.png)
![告警记录界面的下拉列表里面就会多一个启动或停止的告警名称](https://user-images.githubusercontent.com/10259043/86126568-1e92d980-bb11-11ea-9b67-bb035d95adaf.png)

**Comment by gyf520** [comment]
已修复并提交，可拉取代码更新后进行验证
