### ISSUE TITLE
👑 [需求] 设备列表中的字段可选择

### ISSUE THREAD

**Issue by turandot2017** [jetlinks/jetlinks-ui-antd#97]
### 🥰 需求描述

 Jetlinks中可通过 型号-物模型-标签 定义设备的`扩展字段`
 很多时候, 有指定的应用中有一些公共的`业务字段`, 如厂商
 这些非运行时关键字段对于业务而言是关键字段, 需要在列表中进行直接显示
目前只能通过 设备列表--查看 二级进入, 虽然增加了标签查询, 但与实际用户需求有一定的距离
建议:
1. 能做成相对灵活的列表展示, 可以将标签中的某些标签内容直接显示到列表中, 提高用户体验
2. 作为表格显示, 用户可选择`显示隐藏哪些列`, 增加灵活性
这个设备实例列表, 应该是系统中使用频率最高的界面--尤其在上线运行后

### 🧐 解决方案

1. 对实例列表的查询API进行优化, 有一定的配置功能, 支持标签字段作为扩展字段的直接显示
2. 支持`列显隐` 功能

前端Grid参考:
https://avuejs.com/doc/crud/crud

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/27339520/86423780-389c0a00-bd13-11ea-9cd9-c6b2ee844be8.png)

**Comment by zhou-hao** [comment]
已加入候选任务。
